# Generated by Django 5.2.6 on 2025-09-15 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='firstname', max_length=50)),
                ('last_name', models.CharField(default='lastname', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('city', models.CharField(default='city', max_length=50)),
                ('pincode', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='firstname', max_length=50)),
                ('last_name', models.CharField(default='lastname', max_length=50)),
                ('store_name', models.CharField(default='storename', max_length=100)),
                ('store_type', models.CharField(choices=[('grocery', 'Grocery & General Store'), ('clothing', 'Clothing & Fashion'), ('electronics', 'Electronics & Appliances'), ('pharmacy', 'Pharmacy & Health'), ('stationery', 'Stationery & Books'), ('Furniture', 'Furniture & Home Decor'), ('jewelry', 'Jewelry & Accessories'), ('sports', 'Sports & Fitness'), ('toys', 'Toys & Baby Products'), ('bakery', 'Bakery & Confectionery'), ('restaurant', 'Restaurant & Food Outlet'), ('beauty', 'Beauty & Personal Care'), ('automobile', 'Automobile Parts & Accessories'), ('others', 'Others')], default='grocery', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('city', models.CharField(default='city', max_length=50)),
                ('pincode', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('customer', 'Customer')], default='customer', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
