# Generated by Django 5.2.6 on 2025-09-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='store_type',
            field=models.CharField(choices=[('grocery', 'Grocery & General Store'), ('clothing', 'Clothing & Fashion'), ('Electronics & Appliances', 'electronics'), ('pharmacy', 'Pharmacy & Health'), ('stationery', 'Stationery & Books'), ('Furniture', 'Furniture & Home Decor'), ('jewelry', 'Jewelry & Accessories'), ('sports', 'Sports & Fitness'), ('toys', 'Toys & Baby Products'), ('bakery', 'Bakery & Confectionery'), ('restaurant', 'Restaurant & Food Outlet'), ('beauty', 'Beauty & Personal Care'), ('automobile', 'Automobile Parts & Accessories'), ('others', 'Others')], default='grocery', max_length=50),
        ),
    ]
