# Generated by Django 5.2.6 on 2025-09-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginManager', '0002_alter_vendorprofile_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='store_type',
            field=models.CharField(choices=[('Grocery & General Store', 'grocery'), ('Clothing & Fashion', 'clothing'), ('Electronics & Appliances', 'electronics'), ('Pharmacy & Health', 'pharmacy'), ('Stationery & Books', 'stationery'), ('Furniture & Home Decor', 'Furniture'), ('Jewelry & Accessories', 'jewelry'), ('Sports & Fitness', 'sports'), ('Toys & Baby Products', 'toys'), ('Bakery & Confectionery', 'bakery'), ('Restaurant & Food Outlet', 'restaurant'), ('Beauty & Personal Care', 'beauty'), ('Automobile Parts & Accessories', 'automobile'), ('Others', 'others')], default='grocery', max_length=50),
        ),
    ]
